/**
 * Bengaluru AI Atlas — dataset.
 *
 * Two exports drive the whole map:
 *   AREAS    — the camera destinations in the left rail, in nav order.
 *   STARTUPS — one record per company pin.
 *
 * Placement note: pins are positioned at *neighbourhood* level, not at exact
 * street addresses. Bengaluru's tech geography is cluster-shaped (Koramangala,
 * HSR, the ORR arc), so a company sits inside the pocket it actually works in
 * rather than on a surveyed rooftop. Corrections are welcome — see CONTRIBUTING.
 */

export const DATA_SOURCES = {
  label: "Public filings, company sites & press",
  updated: "August 2026",
  contribute: "https://github.com/pradeepj/bengaluru-ai-atlas/blob/main/CONTRIBUTING.md",
  repo: "https://github.com/pradeepj/bengaluru-ai-atlas",
};

/**
 * focus: the camera target for each area.
 *   lat/lng  — where the camera looks
 *   distance — how far back the camera sits (world units, 1 unit ≈ 150 m)
 *   height   — camera elevation
 *   rotation — orbital angle in radians, so each area gets its own vantage
 */
export const AREAS = [
  {
    id: "all",
    number: "01",
    label: "The Whole Plateau",
    shortLabel: "Whole Plateau",
    focus: { lat: 12.9452, lng: 77.6415, distance: 176, height: 120, rotation: 0.5 },
    description:
      "58 AI companies across eight clusters. Foundation labs, voice agents, health diagnostics, robotics and agri-intelligence — spread over 25 km of plateau, from Hebbal in the north to Electronic City in the south.",
  },
  {
    id: "koramangala",
    number: "02",
    label: "Koramangala",
    shortLabel: "Koramangala",
    focus: { lat: 12.9345, lng: 77.6250, distance: 46, height: 44, rotation: 0.38 },
    description:
      "The origin block. India's densest concentration of founders per square kilometre, and now the address for its frontier model labs. Sarvam and Krutrim sit within walking distance of the cafés where half the ecosystem was raised.",
  },
  {
    id: "hsr-sarjapur",
    number: "03",
    label: "HSR Layout / Sarjapur Road",
    shortLabel: "HSR / Sarjapur",
    focus: { lat: 12.9118, lng: 77.6500, distance: 48, height: 45, rotation: 0.5 },
    description:
      "The hacker-house belt. Cheaper rent than Koramangala, a sector grid full of coworking floors, and the highest density of seed-stage AI teams on the map — inference infra, agent tooling, voice, agritech.",
  },
  {
    id: "indiranagar",
    number: "04",
    label: "Indiranagar / Domlur",
    shortLabel: "Indiranagar",
    focus: { lat: 12.9700, lng: 77.6395, distance: 44, height: 42, rotation: 0.68 },
    description:
      "Applied AI on the old cantonment grid. Creative tooling, emotion and vision research, and regtech, tucked into converted bungalows between 100 Feet Road and the Domlur flyover.",
  },
  {
    id: "orr",
    number: "05",
    label: "Outer Ring Road Arc",
    shortLabel: "ORR Arc",
    focus: { lat: 12.9400, lng: 77.6880, distance: 62, height: 54, rotation: 0.92 },
    description:
      "The corporate spine: Bellandur through Kadubeesanahalli to Marathahalli. Glass parks on the lake edge, where the late-stage operators and the global research labs keep their floors.",
  },
  {
    id: "whitefield",
    number: "06",
    label: "Whitefield / ITPL",
    shortLabel: "Whitefield",
    focus: { lat: 12.9755, lng: 77.7345, distance: 50, height: 46, rotation: 1.06 },
    description:
      "Eighteen kilometres east of the centre, a campus city of its own. Enterprise analytics, diagnostics and adoption platforms, anchored to the tech parks around ITPL.",
  },
  {
    id: "cbd",
    number: "07",
    label: "CBD / MG Road",
    shortLabel: "CBD",
    focus: { lat: 12.9775, lng: 77.6035, distance: 44, height: 43, rotation: 0.28 },
    description:
      "The old core, between Cubbon Park and the Vidhana Soudha. Regulated-world AI — health diagnostics, financial data, enterprise agents — plus the research lab that trained a generation of Indian ML engineers.",
  },
  {
    id: "north",
    number: "08",
    label: "North: Hebbal / IISc",
    shortLabel: "North",
    focus: { lat: 13.0330, lng: 77.5940, distance: 64, height: 56, rotation: 0.18 },
    description:
      "Where the hardware lives. Robotics, machine vision and space intelligence cluster around the Indian Institute of Science and the Hebbal corridor out to the airport.",
  },
  {
    id: "south",
    number: "09",
    label: "South: Electronic City",
    shortLabel: "South",
    focus: { lat: 12.8760, lng: 77.6280, distance: 68, height: 58, rotation: 0.72 },
    description:
      "The original tech township, twenty kilometres down Hosur Road. Services-scale AI at the bottom of the map, with health and geospatial teams filling in JP Nagar and Bannerghatta Road.",
  },
];

/**
 * Company records.
 *   stage:  Early-Stage | Late-Stage | Public | Research
 *   office: HQ | Satellite Office
 *   blurb:  one line on what they actually build
 */
export const STARTUPS = [
  // ── Koramangala ───────────────────────────────────────────────────────────
  {
    id: "sarvam-ai",
    name: "Sarvam AI",
    lat: 12.9345,
    lng: 77.6215,
    area: "koramangala",
    stage: "Late-Stage",
    sector: "Foundation Models",
    office: "HQ",
    website: "https://www.sarvam.ai/",
    founded: 2023,
    blurb:
      "Sovereign foundation models built for Indian languages, and the country's most-watched frontier lab.",
  },
  {
    id: "krutrim",
    name: "Krutrim",
    lat: 12.9302,
    lng: 77.6288,
    area: "koramangala",
    stage: "Late-Stage",
    sector: "AI/Data Infrastructure",
    office: "HQ",
    website: "https://www.olakrutrim.com/",
    founded: 2023,
    blurb:
      "Ola's AI arm, now concentrated on AI cloud infrastructure for Indian model builders.",
  },
  {
    id: "dashtoon",
    name: "Dashtoon",
    lat: 12.9378,
    lng: 77.6262,
    area: "koramangala",
    stage: "Early-Stage",
    sector: "Media/Creative",
    office: "HQ",
    website: "https://dashtoon.com/",
    founded: 2022,
    blurb: "Generative comics — a studio pipeline that turns scripts into illustrated panels.",
  },
  {
    id: "toplyne",
    name: "Toplyne",
    lat: 12.9328,
    lng: 77.6172,
    area: "koramangala",
    stage: "Early-Stage",
    sector: "Enterprise Automation",
    office: "HQ",
    website: "https://www.toplyne.io/",
    founded: 2021,
    blurb: "AI go-to-market: scores product usage to tell sales teams who is ready to buy.",
  },
  {
    id: "verloop",
    name: "Verloop.io",
    lat: 12.9392,
    lng: 77.6305,
    area: "koramangala",
    stage: "Early-Stage",
    sector: "AI Interface",
    office: "HQ",
    website: "https://verloop.io/",
    founded: 2016,
    blurb: "Conversational support automation for chat and voice, heavy on Indic languages.",
  },
  {
    id: "karya",
    name: "Karya",
    lat: 12.9288,
    lng: 77.6188,
    area: "koramangala",
    stage: "Early-Stage",
    sector: "AI/Data Infrastructure",
    office: "HQ",
    website: "https://www.karya.in/",
    founded: 2021,
    blurb:
      "Ethical data work — pays rural Indian speakers to build the speech corpora that low-resource models need.",
  },
  {
    id: "zluri",
    name: "Zluri",
    lat: 12.9415,
    lng: 77.6228,
    area: "koramangala",
    stage: "Early-Stage",
    sector: "Enterprise Automation",
    office: "HQ",
    website: "https://www.zluri.com/",
    founded: 2020,
    blurb: "Discovers and governs every SaaS app and identity inside an enterprise.",
  },
  {
    id: "vahan",
    name: "Vahan.ai",
    lat: 12.9268,
    lng: 77.6238,
    area: "koramangala",
    stage: "Early-Stage",
    sector: "AI Application",
    office: "HQ",
    website: "https://vahan.ai/",
    founded: 2016,
    blurb: "AI recruiter that hires India's blue-collar workforce over chat, at gig-economy scale.",
  },

  // ── HSR Layout / Sarjapur Road ────────────────────────────────────────────
  {
    id: "composio",
    name: "Composio",
    lat: 12.9158,
    lng: 77.6418,
    area: "hsr-sarjapur",
    stage: "Early-Stage",
    sector: "DevOps",
    office: "HQ",
    website: "https://composio.dev/",
    founded: 2023,
    blurb: "Tool-calling infrastructure — plugs agents into hundreds of apps with managed auth.",
  },
  {
    id: "simplismart",
    name: "Simplismart",
    lat: 12.9118,
    lng: 77.6458,
    area: "hsr-sarjapur",
    stage: "Early-Stage",
    sector: "AI/Data Infrastructure",
    office: "HQ",
    website: "https://www.simplismart.ai/",
    founded: 2022,
    blurb: "Fast inference engine for teams that want to serve open models cheaply.",
  },
  {
    id: "nurix-ai",
    name: "Nurix AI",
    lat: 12.9092,
    lng: 77.6502,
    area: "hsr-sarjapur",
    stage: "Early-Stage",
    sector: "AI Interface",
    office: "HQ",
    website: "https://www.nurix.ai/",
    founded: 2024,
    blurb: "Real-time voice agents for enterprise support, built for low-latency phone calls.",
  },
  {
    id: "segmind",
    name: "Segmind",
    lat: 12.9184,
    lng: 77.6482,
    area: "hsr-sarjapur",
    stage: "Early-Stage",
    sector: "AI/Data Infrastructure",
    office: "HQ",
    website: "https://www.segmind.com/",
    founded: 2020,
    blurb: "Generative-media infrastructure: hosted pipelines for image and video models.",
  },
  {
    id: "cropin",
    name: "Cropin",
    lat: 12.9072,
    lng: 77.6392,
    area: "hsr-sarjapur",
    stage: "Late-Stage",
    sector: "Agriculture",
    office: "HQ",
    website: "https://www.cropin.com/",
    founded: 2010,
    blurb:
      "Agri-intelligence from satellite and field data — yield, disease and weather models over millions of acres.",
  },
  {
    id: "wysa",
    name: "Wysa",
    lat: 12.9142,
    lng: 77.6368,
    area: "hsr-sarjapur",
    stage: "Early-Stage",
    sector: "Healthcare",
    office: "HQ",
    website: "https://www.wysa.com/",
    founded: 2016,
    blurb: "Clinically-evaluated conversational agent for mental health support.",
  },
  {
    id: "emergent",
    name: "Emergent",
    lat: 12.9204,
    lng: 77.6522,
    area: "hsr-sarjapur",
    stage: "Early-Stage",
    sector: "Coding",
    office: "HQ",
    website: "https://emergent.sh/",
    founded: 2023,
    blurb: "Agentic app builder — describe software in prose and it ships the running product.",
  },
  {
    id: "bolna",
    name: "Bolna",
    lat: 12.9218,
    lng: 77.6588,
    area: "hsr-sarjapur",
    stage: "Early-Stage",
    sector: "AI Interface",
    office: "HQ",
    website: "https://www.bolna.dev/",
    founded: 2023,
    blurb: "Open-source framework for building and running production voice agents.",
  },
  {
    id: "bureau",
    name: "Bureau",
    lat: 12.9232,
    lng: 77.6442,
    area: "hsr-sarjapur",
    stage: "Early-Stage",
    sector: "Financial Services",
    office: "HQ",
    website: "https://www.bureau.id/",
    founded: 2020,
    blurb: "Identity decisioning and fraud risk scored from device, behaviour and network signals.",
  },
  {
    id: "mfine",
    name: "MFine",
    lat: 12.9048,
    lng: 77.6558,
    area: "hsr-sarjapur",
    stage: "Late-Stage",
    sector: "Healthcare",
    office: "HQ",
    website: "https://www.mfine.co/",
    founded: 2017,
    blurb: "AI-assisted virtual care, routing patients to specialists and reading their scans.",
  },
  {
    id: "skit-ai",
    name: "Skit.ai",
    lat: 12.9032,
    lng: 77.6628,
    area: "hsr-sarjapur",
    stage: "Early-Stage",
    sector: "AI Interface",
    office: "HQ",
    website: "https://skit.ai/",
    founded: 2016,
    blurb: "Voice-AI collections and outreach for lenders, formerly Vernacular.ai.",
  },

  // ── Indiranagar / Domlur ──────────────────────────────────────────────────
  {
    id: "entropik",
    name: "Entropik",
    lat: 12.9642,
    lng: 77.6398,
    area: "indiranagar",
    stage: "Early-Stage",
    sector: "AI Application",
    office: "HQ",
    website: "https://www.entropik.io/",
    founded: 2016,
    blurb: "Emotion AI for research — reads facial, voice and eye signals to test products.",
  },
  {
    id: "slang-labs",
    name: "Slang Labs",
    lat: 12.9724,
    lng: 77.6412,
    area: "indiranagar",
    stage: "Early-Stage",
    sector: "AI Interface",
    office: "HQ",
    website: "https://www.slanglabs.in/",
    founded: 2017,
    blurb: "Multilingual voice assistants dropped into existing consumer apps.",
  },
  {
    id: "rocketium",
    name: "Rocketium",
    lat: 12.9662,
    lng: 77.6358,
    area: "indiranagar",
    stage: "Early-Stage",
    sector: "Media/Creative",
    office: "HQ",
    website: "https://rocketium.com/",
    founded: 2016,
    blurb: "Creative automation — generates and versions ad campaigns at brand scale.",
  },
  {
    id: "wobot",
    name: "Wobot.ai",
    lat: 12.9782,
    lng: 77.6432,
    area: "indiranagar",
    stage: "Early-Stage",
    sector: "Security",
    office: "HQ",
    website: "https://wobot.ai/",
    founded: 2017,
    blurb: "Video intelligence layered over existing CCTV to audit operational compliance.",
  },
  {
    id: "neuropixel",
    name: "Neuropixel.ai",
    lat: 12.9602,
    lng: 77.6338,
    area: "indiranagar",
    stage: "Early-Stage",
    sector: "Media/Creative",
    office: "HQ",
    website: "https://neuropixel.ai/",
    founded: 2021,
    blurb: "Generative product imagery for e-commerce catalogues, without the photoshoot.",
  },
  {
    id: "signzy",
    name: "Signzy",
    lat: 12.9758,
    lng: 77.6468,
    area: "indiranagar",
    stage: "Early-Stage",
    sector: "Financial Services",
    office: "HQ",
    website: "https://www.signzy.com/",
    founded: 2015,
    blurb: "AI onboarding and KYC rails used across Indian banking.",
  },

  // ── Outer Ring Road Arc ───────────────────────────────────────────────────
  {
    id: "yellow-ai",
    name: "Yellow.ai",
    lat: 12.9268,
    lng: 77.6792,
    area: "orr",
    stage: "Late-Stage",
    sector: "AI Interface",
    office: "HQ",
    website: "https://yellow.ai/",
    founded: 2016,
    blurb: "Enterprise conversational platform running customer and employee agents in 100+ languages.",
  },
  {
    id: "observe-ai",
    name: "Observe.AI",
    lat: 12.9334,
    lng: 77.6872,
    area: "orr",
    stage: "Late-Stage",
    sector: "AI Application",
    office: "HQ",
    website: "https://www.observe.ai/",
    founded: 2017,
    blurb: "Contact-centre intelligence — transcribes, scores and coaches every support call.",
  },
  {
    id: "netradyne",
    name: "Netradyne",
    lat: 12.9424,
    lng: 77.6962,
    area: "orr",
    stage: "Late-Stage",
    sector: "Manufacturing & Industrials",
    office: "HQ",
    website: "https://www.netradyne.com/",
    founded: 2015,
    blurb: "Edge vision for commercial fleets, grading driver behaviour from the windshield.",
  },
  {
    id: "nvidia-blr",
    name: "NVIDIA Bengaluru",
    lat: 12.9538,
    lng: 77.7008,
    area: "orr",
    stage: "Public",
    sector: "AI/Data Infrastructure",
    office: "Satellite Office",
    website: "https://www.nvidia.com/en-in/",
    blurb: "One of NVIDIA's largest engineering sites outside the US — silicon, drivers and AI software.",
  },
  {
    id: "tessell",
    name: "Tessell",
    lat: 12.9378,
    lng: 77.6928,
    area: "orr",
    stage: "Early-Stage",
    sector: "AI/Data Infrastructure",
    office: "HQ",
    website: "https://www.tessell.com/",
    founded: 2021,
    blurb: "Managed multi-cloud database platform, built by ex-Oracle infrastructure engineers.",
  },
  {
    id: "locus",
    name: "Locus",
    lat: 12.9298,
    lng: 77.6732,
    area: "orr",
    stage: "Late-Stage",
    sector: "Enterprise Automation",
    office: "HQ",
    website: "https://locus.sh/",
    founded: 2015,
    blurb: "Route optimisation and dispatch intelligence for last-mile logistics fleets.",
  },
  {
    id: "eightfold",
    name: "Eightfold.ai",
    lat: 12.9482,
    lng: 77.6888,
    area: "orr",
    stage: "Late-Stage",
    sector: "Enterprise Automation",
    office: "Satellite Office",
    website: "https://eightfold.ai/",
    blurb: "Talent-intelligence platform; Bengaluru is its principal engineering centre.",
  },
  {
    id: "gupshup",
    name: "Gupshup",
    lat: 12.9444,
    lng: 77.6788,
    area: "orr",
    stage: "Late-Stage",
    sector: "AI Interface",
    office: "HQ",
    website: "https://www.gupshup.io/",
    founded: 2004,
    blurb: "Conversational commerce at carrier scale — billions of business messages a month.",
  },
  {
    id: "samsung-sri-b",
    name: "Samsung R&D Institute India",
    lat: 12.9808,
    lng: 77.6978,
    area: "orr",
    stage: "Public",
    sector: "AI/Data Infrastructure",
    office: "Satellite Office",
    website: "https://research.samsung.com/sri-b",
    blurb: "Samsung's largest R&D centre outside Korea; on-device AI, vision and speech.",
  },
  {
    id: "jiva-ag",
    name: "Jiva.ag",
    lat: 12.9352,
    lng: 77.7052,
    area: "orr",
    stage: "Early-Stage",
    sector: "Agriculture",
    office: "HQ",
    website: "https://jiva.ag/",
    founded: 2019,
    blurb: "Crop advisory and agri-credit scoring for smallholder farmers across South Asia.",
  },

  // ── Whitefield / ITPL ─────────────────────────────────────────────────────
  {
    id: "sigtuple",
    name: "SigTuple",
    lat: 12.9762,
    lng: 77.7282,
    area: "whitefield",
    stage: "Early-Stage",
    sector: "Healthcare",
    office: "HQ",
    website: "https://sigtuple.com/",
    founded: 2015,
    blurb: "Robotic microscopy — automates blood, urine and semen analysis in pathology labs.",
  },
  {
    id: "avaamo",
    name: "Avaamo",
    lat: 12.9844,
    lng: 77.7402,
    area: "whitefield",
    stage: "Early-Stage",
    sector: "AI Interface",
    office: "HQ",
    website: "https://avaamo.ai/",
    founded: 2014,
    blurb: "Conversational AI for regulated enterprises, with deep healthcare deployments.",
  },
  {
    id: "whatfix",
    name: "Whatfix",
    lat: 12.9704,
    lng: 77.7188,
    area: "whitefield",
    stage: "Late-Stage",
    sector: "Enterprise Automation",
    office: "HQ",
    website: "https://whatfix.com/",
    founded: 2014,
    blurb: "Digital adoption — in-app guidance and AI copilots layered over enterprise software.",
  },
  {
    id: "thoughtspot",
    name: "ThoughtSpot",
    lat: 12.9658,
    lng: 77.7462,
    area: "whitefield",
    stage: "Late-Stage",
    sector: "AI/Data Infrastructure",
    office: "HQ",
    website: "https://www.thoughtspot.com/",
    founded: 2012,
    blurb: "Search-and-AI analytics; founded in Bengaluru and still its biggest engineering base.",
  },
  {
    id: "google-research-india",
    name: "Google Research India",
    lat: 12.9888,
    lng: 77.7252,
    area: "whitefield",
    stage: "Public",
    sector: "AI/Data Infrastructure",
    office: "Satellite Office",
    website: "https://research.google/locations/india/",
    blurb: "Google's India AI lab — Indic languages, speech, and societal-scale ML.",
  },
  {
    id: "corover",
    name: "CoRover.ai",
    lat: 12.9792,
    lng: 77.7522,
    area: "whitefield",
    stage: "Early-Stage",
    sector: "AI Interface",
    office: "HQ",
    website: "https://corover.ai/",
    founded: 2016,
    blurb: "Builder of AskDISHA — the multilingual assistant handling IRCTC's passenger queries.",
  },

  // ── CBD / MG Road ─────────────────────────────────────────────────────────
  {
    id: "microsoft-research-india",
    name: "Microsoft Research India",
    lat: 12.9708,
    lng: 77.5958,
    area: "cbd",
    stage: "Public",
    sector: "AI/Data Infrastructure",
    office: "Satellite Office",
    website: "https://www.microsoft.com/en-us/research/lab/microsoft-research-india/",
    blurb: "Lavelle Road lab behind Project Karya and much of India's applied-ML research lineage.",
  },
  {
    id: "perfios",
    name: "Perfios",
    lat: 12.9822,
    lng: 77.6012,
    area: "cbd",
    stage: "Late-Stage",
    sector: "Financial Services",
    office: "HQ",
    website: "https://www.perfios.com/",
    founded: 2008,
    blurb: "Financial-data analytics powering underwriting for most large Indian lenders.",
  },
  {
    id: "ema",
    name: "Ema",
    lat: 12.9882,
    lng: 77.5992,
    area: "cbd",
    stage: "Late-Stage",
    sector: "Enterprise Automation",
    office: "HQ",
    website: "https://www.ema.co/",
    founded: 2023,
    blurb: "A 'universal AI employee' that takes on whole enterprise workflows end to end.",
  },
  {
    id: "niramai",
    name: "Niramai",
    lat: 12.9752,
    lng: 77.6082,
    area: "cbd",
    stage: "Early-Stage",
    sector: "Healthcare",
    office: "HQ",
    website: "https://www.niramai.com/",
    founded: 2016,
    blurb: "Radiation-free breast-cancer screening from thermal images and ML.",
  },
  {
    id: "5c-network",
    name: "5C Network",
    lat: 12.9682,
    lng: 77.6122,
    area: "cbd",
    stage: "Early-Stage",
    sector: "Healthcare",
    office: "HQ",
    website: "https://www.5cnetwork.com/",
    founded: 2016,
    blurb: "Teleradiology network with AI triage, reading scans for hospitals across small-town India.",
  },
  {
    id: "tricog",
    name: "Tricog Health",
    lat: 12.9928,
    lng: 77.6052,
    area: "cbd",
    stage: "Late-Stage",
    sector: "Healthcare",
    office: "HQ",
    website: "https://www.tricog.com/",
    founded: 2014,
    blurb: "Cloud ECG interpretation that flags heart attacks in minutes from rural clinics.",
  },

  // ── North: Hebbal / IISc ──────────────────────────────────────────────────
  {
    id: "artpark",
    name: "ARTPARK",
    lat: 13.0218,
    lng: 77.5668,
    area: "north",
    stage: "Research",
    sector: "Research",
    office: "HQ",
    website: "https://www.artpark.in/",
    founded: 2020,
    blurb: "IISc's AI & Robotics Technology Park — public-mission research and a hardware foundry.",
  },
  {
    id: "cynlr",
    name: "CynLr",
    lat: 13.0304,
    lng: 77.5812,
    area: "north",
    stage: "Early-Stage",
    sector: "Manufacturing & Industrials",
    office: "HQ",
    website: "https://www.cynlr.com/",
    founded: 2019,
    blurb: "Visual object intelligence — robot hands that can pick an unfamiliar object cold.",
  },
  {
    id: "ati-motors",
    name: "Ati Motors",
    lat: 13.0408,
    lng: 77.6122,
    area: "north",
    stage: "Early-Stage",
    sector: "Manufacturing & Industrials",
    office: "HQ",
    website: "https://atimotors.com/",
    founded: 2017,
    blurb: "Autonomous cargo robots hauling material across factory floors worldwide.",
  },
  {
    id: "digantara",
    name: "Digantara",
    lat: 13.0482,
    lng: 77.5862,
    area: "north",
    stage: "Early-Stage",
    sector: "Manufacturing & Industrials",
    office: "HQ",
    website: "https://www.digantara.co.in/",
    founded: 2018,
    blurb: "Space situational awareness — tracking orbital objects and modelling collision risk.",
  },
  {
    id: "ambee",
    name: "Ambee",
    lat: 13.0128,
    lng: 77.5928,
    area: "north",
    stage: "Early-Stage",
    sector: "AI/Data Infrastructure",
    office: "HQ",
    website: "https://www.getambee.com/",
    founded: 2017,
    blurb: "Hyperlocal environmental intelligence: air quality, pollen and climate risk as an API.",
  },
  {
    id: "fractal-blr",
    name: "Fractal (Bengaluru)",
    lat: 13.0398,
    lng: 77.6208,
    area: "north",
    stage: "Late-Stage",
    sector: "AI Application",
    office: "Satellite Office",
    website: "https://fractal.ai/",
    blurb: "India's largest enterprise-AI services firm; Manyata is one of its main delivery hubs.",
  },

  // ── South: Electronic City ────────────────────────────────────────────────
  {
    id: "infosys-topaz",
    name: "Infosys Topaz",
    lat: 12.8458,
    lng: 77.6622,
    area: "south",
    stage: "Public",
    sector: "AI Application",
    office: "Satellite Office",
    website: "https://www.infosys.com/services/data-ai-topaz.html",
    blurb: "Infosys' AI practice, run from the Electronic City campus that started the township.",
  },
  {
    id: "healthplix",
    name: "HealthPlix",
    lat: 12.9088,
    lng: 77.5852,
    area: "south",
    stage: "Early-Stage",
    sector: "Healthcare",
    office: "HQ",
    website: "https://healthplix.com/",
    founded: 2014,
    blurb: "AI-assisted EMR that lets doctors finish a prescription in under a minute.",
  },
  {
    id: "skylark-drones",
    name: "Skylark Drones",
    lat: 12.9042,
    lng: 77.5928,
    area: "south",
    stage: "Early-Stage",
    sector: "Manufacturing & Industrials",
    office: "HQ",
    website: "https://www.skylarkdrones.com/",
    founded: 2014,
    blurb: "Drone survey data turned into mine, solar and infrastructure intelligence.",
  },
  {
    id: "predible",
    name: "Predible",
    lat: 12.8882,
    lng: 77.5978,
    area: "south",
    stage: "Early-Stage",
    sector: "Healthcare",
    office: "HQ",
    website: "https://predible.health/",
    founded: 2016,
    blurb: "Radiology AI for lung, liver and prostate — segmentation that surgeons plan against.",
  },
  {
    id: "pixxel",
    name: "Pixxel",
    lat: 12.8628,
    lng: 77.6252,
    area: "south",
    stage: "Late-Stage",
    sector: "Manufacturing & Industrials",
    office: "HQ",
    website: "https://www.pixxel.space/",
    founded: 2019,
    blurb: "Hyperspectral imaging constellation, with an AI analytics stack reading the planet's chemistry.",
  },
];

/**
 * Pin colour + legend keys, driven by office type.
 *   color      — night-board colour (also the CSS --pin-* dark value)
 *   lightColor — paper-board colour; deeper, or the dots wash out on cream
 *   cssVar     — token the HUD dots use, so CSS swaps them with the theme
 */
export const PIN_KINDS = [
  {
    id: "HQ",
    label: "Headquarters",
    color: "#ffd11a",
    lightColor: "#c8960c",
    cssVar: "--pin-hq",
  },
  {
    id: "Satellite Office",
    label: "Satellite / research office",
    color: "#4d9fff",
    lightColor: "#0e7fd4",
    cssVar: "--pin-satellite",
  },
];

export const SECTORS = [...new Set(STARTUPS.map((s) => s.sector))].sort();

/**
 * One hue per sector, used as an accent in the HUD (company card, search rows)
 * — not on the map, where colour already means office type. Chosen to stay
 * distinguishable against both the night panels and the paper ones, so a single
 * value works in either theme.
 */
export const SECTOR_COLORS = {
  "Foundation Models": "#ff8a4c",
  "AI/Data Infrastructure": "#4ea8f5",
  "AI Interface": "#38c9b0",
  "AI Application": "#7c9cf5",
  "Enterprise Automation": "#a982ec",
  Healthcare: "#f2607f",
  "Financial Services": "#41b866",
  "Media/Creative": "#e8639f",
  "Manufacturing & Industrials": "#c98f3e",
  Agriculture: "#7fb63a",
  Coding: "#5ec2e0",
  DevOps: "#63b8c4",
  Security: "#e0644f",
  Research: "#9d94e8",
};

export function sectorColor(sector) {
  return SECTOR_COLORS[sector] ?? "#8b95a5";
}

export function startupsByArea(areaId) {
  if (areaId === "all") return STARTUPS;
  return STARTUPS.filter((s) => s.area === areaId);
}

export function areaById(areaId) {
  return AREAS.find((a) => a.id === areaId) ?? AREAS[0];
}
